namespace ZeroMQ.Proxy
{
    internal enum ErrorCode
    {
        Eperm = 1,
        Enoent = 2,
        Esrch = 3,
        Eintr = 4,
        Eio = 5,
        Enxio = 6,
        E2Big = 7,
        Enoexec = 8,
        Ebadf = 9,
        Echild = 10,
        Eagain = 11,
        Enomem = 12,
        Eacces = 13,
        Efault = 14,
        Ebusy = 16,
        Eexist = 17,
        Exdev = 18,
        Enodev = 19,
        Enotdir = 20,
        Eisdir = 21,
        Enfile = 23,
        Emfile = 24,
        Enotty = 25,
        Efbig = 27,
        Enospc = 28,
        Espipe = 29,
        Erofs = 30,
        Emlink = 31,
        Epipe = 32,
        Edom = 33,
        Edeadlk = 36,
        Enametoolong = 38,
        Enolck = 39,
        Enosys = 40,
        Enotempty = 41,
        Eaddrinuse = 100,
        Eaddrnotavail = 101,
        Econnrefused = 107,
        Einprogress = 112,
        Enetdown = 116,
        Enobufs = 119,
        Enotsock = 128,
        Enotsup = 129,
        Eprotonosupport = 135,

        // Native 0MQ error codes
        ZmqHausNumero = 156384712,
        Efsm = ZmqHausNumero + 51,
        Enocompatproto = ZmqHausNumero + 52,
        Eterm = ZmqHausNumero + 53,
        Emthread = ZmqHausNumero + 54,
    }
}
