namespace ZeroMQ.Proxy
{
    internal enum ErrorCode
    {
        Eperm = 1,
        Enoent = 2,
        Esrch = 3,
        Eintr = 4,
        Eio = 5,
        Enxio = 6,
        E2Big = 7,
        Enoexec = 8,
        Ebadf = 9,
        Echild = 10,
        Eagain = 11,
        Enomem = 12,
        Eacces = 13,
        Efault = 14,
        Ebusy = 16,
        Eexist = 17,
        Exdev = 18,
        Enodev = 19,
        Enotdir = 20,
        Eisdir = 21,
        Enfile = 23,
        Emfile = 24,
        Enotty = 25,
        Efbig = 27,
        Enospc = 28,
        Espipe = 29,
        Erofs = 30,
        Emlink = 31,
        Epipe = 32,
        Edom = 33,
        Edeadlk = 36,
        Enametoolong = 38,
        Enolck = 39,
        Enosys = 40,
        Enotempty = 41,

        ZmqHausNumero = 156384712,

        // Some of the standard POSIX errnos are not defined on Windows
        Enotsup = ZmqHausNumero + 1,
        Eprotonosupport = ZmqHausNumero + 2,
        Enobufs = ZmqHausNumero + 3,
        Enetdown = ZmqHausNumero + 4,
        Eaddrinuse = ZmqHausNumero + 5,
        Eaddrnotavail = ZmqHausNumero + 6,
        Econnrefused = ZmqHausNumero + 7,
        Einprogress = ZmqHausNumero + 8,
        Enotsock = ZmqHausNumero + 9,

        // Native 0MQ error codes
        Efsm = ZmqHausNumero + 51,
        Enocompatproto = ZmqHausNumero + 52,
        Eterm = ZmqHausNumero + 53,
        Emthread = ZmqHausNumero + 54,
    }
}
